### ISSUE TITLE
Hello For Batch input why did you use the MXPredReshape function instead of the load every time?

### ISSUE THREAD

**Issue by SyGoing** [njvisionpower/mxnet-mtcnn-cpp#1]
The question is the title

**Comment by njvisionpower** [comment]
Hi,

Load model will load parameters from disk to memory which cause overhead. Official mxnet didn't give the automatic reshape operator like python. You can implement that with C++ interface. A better way for C++ inference is initialize specified shape model. For example, batch inference will faster than loop inference one by one, if you want optimize pnet, you can prepare model bind with batch num=8 (or 16, 32 depends on real environment) and num=1, then do inference with batch number and the rest for num 1. I have tested that will speed up about 20% ~30% for rnet and onet.

**Comment by SyGoing** [comment]
Thanks for your reply, I will have a try for that
